plugins: ['@semantic-release/commit-analyzer',
          '@semantic-release/release-notes-generator',
          '@semantic-release/github',
          'gradle-semantic-release-plugin-goldy1992']
branch: develop
ci: false
dryRun: true
debug: true