name: Google Play Store Release
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      KEY_STORE_ALIAS:
        required: true
      KEY_STORE_BASE64:
        required: true
      KEY_STORE_PASSWORD:
        required: true
      RELEASE_SERVICE_ACCOUNT_JSON:
        required: true
      SIGNED_RELEASE_FILE:
        required: true
jobs:
  release:
    env: 
      SIGNING_KEY_FILE: signing_key_file.jks
    runs-on: ubuntu-latest
    environment: release_env
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3.6.0
        with:
          distribution: corretto
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v3.0.11
        with:
          path: |
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up Python 3.9
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.9

      - name: Make generate_signing_key_file.py executable
        run: chmod +x ./.github/ci-scripts/release/generate_signing_key_file.py

      - name: Write Base64 Encoded Key Store value to File Named $SIGNING_KEY_FILE
        run: python ./.github/ci-scripts/release/generate_signing_key_file.py $SIGNING_KEY_FILE ${{ secrets.KEY_STORE_BASE64 }} 
          
      - name: Make $SIGNING_KEY_FILE executable
        run: chmod +x $SIGNING_KEY_FILE

      - name: Build release bundle with Gradle
        run: ./gradlew bundleRelease --stacktrace -PdisablePreDex -Pfull_release_storePassword=${{ secrets.KEY_STORE_PASSWORD }} -Pfull_release_keyAlias=${{ secrets.KEY_ALIAS }} -P=full_release_keyPassword=${{ secrets.KEY_PASSWORD }} -P=full_release_storeFile=$SIGNING_KEY_FILE

      - name: Create service_account.json FROM secrets.SERVICE_ACCOUNT_JSON
        run: echo '${{ secrets.RELEASE_SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Upload signed AAB to Playstore
        uses: r0adkll/upload-google-play@v1.0.19
        with:
          serviceAccountJson: service_account.json
          packageName: com.github.goldy1992.mp3player.full
          releaseFiles: app/build/outputs/bundle/fullRelease/app-full-release.aab
          track: production
          inAppUpdatePriority: 2
          whatsNewDirectory: distrib/whatsnew
          mappingFile: app/build/outputs/mapping/fullRelease/mapping.txt