name: Master Build, Test and Release Workflow
on:
  push:
    branches:
      - master

jobs:
  master-build-and-test:
    uses: ./.github/workflows/master-build-and-ui-test.yml
    secrets:
      RELEASE_SERVICE_ACCOUNT_JSON: ${{ secrets.RELEASE_SERVICE_ACCOUNT_JSON }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  semantic-release:
    needs: [ master-build-and-test ]
    uses: ./.github/workflows/github-semantic-release.yml
    secrets:
      SEMANTIC_RELEASE_FINE_GRAINED_TOKEN: ${{ secrets.SEMANTIC_RELEASE_FINE_GRAINED_TOKEN }}

  release-to-playstore:
    needs: [ semantic-release ] # needs semantic release so that the versions are incremented
    if: needs.semantic-release.outputs.performed_release == 'true'
    uses: ./.github/workflows/google-play-store-release.yml
    with:
      release_commit_ref: needs.semantic-release.outputs.release_commit_ref
    secrets:
      KEY_STORE_BASE64: ${{ secrets.KEY_STORE_BASE64 }}
      KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      RELEASE_SERVICE_ACCOUNT_JSON: ${{ secrets.RELEASE_SERVICE_ACCOUNT_JSON }}