name: Pull Request to master Workflow
run-name: Pull Request to master Workflow
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - master
jobs:
  run-unit-tests:
    name: Build and Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3.6.0
        with:
          distribution: corretto
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v3.0.11
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Cache SonarCloud packages
        uses: actions/cache@v3.0.11
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2.0.10
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Gradle Clean
        run: ./gradlew clean
      - name: Gradle and create Debug test report
        run: ./gradlew createDebugUnitTestCoverageReport
      - name: Gradle and create FullDebug test report
        run: ./gradlew createFullDebugUnitTestCoverageReport
      - name: Run Lint
        run: ./gradlew lint
      - name: Run Sonar
        run: ./gradlew sonar --info --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}