name: Develop Check Run Completed Workflow
on:
  check_run:
    types: [completed]
    branches:
      - develop

jobs:
  merge-to-master-checker:
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
      IS_SONAR_CHECK_RUN: 0
      QUALITY_GATE_PASSED: 0
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Merge develop to master.
        if: ${{ env.IS_SONAR_CHECK_RUN && env.QUALITY_GATE_PASSED }}
        run: echo "Merging to master"

      - name: Dump GitHub context into event.json
        run: echo $GITHUB_CONTEXT | tee event.json;

      - name: Check for Sonar event
        run: |
           export IS_SONAR_CHECK_RUN=$(python3 ./.github/ci-scripts/is_sonar_event.py event.json); \

      - name: Not a Sonar Event
        if: ${{ !env.IS_SONAR_CHECK_RUN }}
        run: echo "Not a sonar check run event."

      - name: Check Sonar Quality Gate
        if: ${{ env.IS_SONAR_CHECK_RUN }}
        run: |
          echo "Sonar check run identified, checking quality gate"; \
          export QUALITY_GATE_PASSED=$(python3 ./.github/ci-scripts/quality_gate_check.py event.json); \

      - name: Quality Gate Failed.
        if: ${{ env.IS_SONAR_CHECK_RUN && !env.QUALITY_GATE_PASSED }}
        run: echo "Quality gate failed!"

      - name: Merging develop to master
        if: ${{ env.IS_SONAR_CHECK_RUN && env.QUALITY_GATE_PASSED }}
        run: |
          echo "Quality Qate passed... Merging to master..."
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/merges \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{"base":"master", "head":"develop"}' \
          --fail


