name: On status Change
on:
  check_run:
    types: [completed]
    branches:
      - develop

jobs:
  test-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Echo's result
        run: echo "completed check suite  ${{ github.event }}"

      - name: testing status
        run: echo hellow

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo $GITHUB_CONTEXT | tee event.json;

      - name: Run Python script.
        run: |
          issuccess=$(python3 ./.github/ci-scripts/analyse_payload_event.py event.json); \
          echo "result is ${issuccess}" \
          if [[ -z $issuccess ]] \
          then \
            echo "Merging to master" \
          else \
            echo "Quality gate failed... NO MERGE" \
          fi \

